steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - -t
      - northamerica-northeast1-docker.pkg.dev/$PROJECT_ID/openmoneyweb/openmoneyweb:latest
      - .

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'northamerica-northeast1-docker.pkg.dev/$PROJECT_ID/openmoneyweb/openmoneyweb:latest']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - openmoneyweb
      - --image=northamerica-northeast1-docker.pkg.dev/$PROJECT_ID/openmoneyweb/openmoneyweb:latest
      - --region=northamerica-northeast1
      - --platform=managed
      - --allow-unauthenticated
      - --add-cloudsql-instances=$PROJECT_ID:northamerica-northeast1:openmoney-db
      - --remove-env-vars=ConnectionStrings__DefaultConnection
      - --set-secrets=ConnectionStrings__DefaultConnection=db-connection-string:latest

images:
  - northamerica-northeast1-docker.pkg.dev/$PROJECT_ID/openmoneyweb/openmoneyweb
